### ISSUE TITLE
Contact names do not show

### ISSUE THREAD

**Issue by tomspeak** [CamHenlin/imessageclient#10]
Would be great if you could bring in the contact's name instead of displaying the raw telephone number / iCloud email address.

**Comment by CamHenlin** [comment]
Yes, I agree! I began working on integration with the AddesssBook SQLite db last night, hopefully will have something to show for it soon

**Comment by CamHenlin** [comment]
Just to update, I believe I have this figured out and will probably have it committed this evening

**Comment by CamHenlin** [comment]
Update! I've got the basics working now. Contact's name now shows at the top of the screen after you select a conversation with them. I don't yet consider this resolved since it still has raw phone numbers in the conversation list

**Comment by TomSpeak** [comment]
:+1:  Great work Sir!

**Comment by hollanddd** [comment]
I love this and think it's awesome. Keep it up. With that said here are my 2 cents. As far as I can tell you are looking up conctact names everytime you select on item in the list of conversations. I feel it would be best to make sense of the contacts when the app initializes. For getNamesFromPhone I would start by selecting all the contacts and filtering them. You want to remove unwanted chars from both instead of trying to do a like find. My node-fu is weak but i'll see if I can't submit a pull request

**Comment by CamHenlin** [comment]
Yeah, I just did the quickest possible thing I could do. Honestly I've been spending more time using the private Messages framework to send messages rather than thinking about detecting names properly. Definitely submit a pull request if you have time, otherwise I'll probably get to it over the next few days (depending on the aforementioned private Messages framework)
